### ISSUE TITLE
Work on new launcher icons

### ISSUE THREAD

**Issue by bikramm** [restart32/ACMPSUAPP#1]

**Comment by bikramm** [comment]
144x144 for extra extra high-density (XXHDPI)
![ic_launcher](https://cloud.githubusercontent.com/assets/1916115/10061433/8b56fa36-620d-11e5-887b-8ee425f259c8.png)

96x96 for extra high-density (XHDPI)
![ic_launcher](https://cloud.githubusercontent.com/assets/1916115/10061436/93878be4-620d-11e5-94e2-75bf1da105af.png)

72x72 for high-density (HDPI)
![ic_launcher](https://cloud.githubusercontent.com/assets/1916115/10061438/9a7eb120-620d-11e5-8926-68bea84282f2.png)

48x48 for medium-density (MDPI)
![ic_launcher](https://cloud.githubusercontent.com/assets/1916115/10061442/9e5a80ee-620d-11e5-8ec1-02388715c048.png)

**Comment by Kiarasht** [comment]
The two larger icons should be of 192 x 192 and another one of 512 x 512 for when the app is uploaded to Google Play store. Usually just having the 512 x 512 is fine since Android Studio itself will scale the image down.

http://stackoverflow.com/a/12768159
